FROM sqlwwx/silk-v3-decoder:latest as builder
FROM sqlwwx/alinode

RUN apk add --no-cache ffmpeg bash

# copy silk-v3-decoder
COPY --from=builder /silk-v3-decoder/converter.sh /silk-v3-decoder/
COPY --from=builder /silk-v3-decoder/silk/decoder /silk-v3-decoder/silk/
